# train configs
EPOCHS = 4
BATCHSIZE = 10
SPECIALKEYS = ["<unk>", "<s>", "</s>", "<pad>"]
UNKSTR = SPECIALKEYS[0]
STARTSTR = SPECIALKEYS[1]
ENDSTR = SPECIALKEYS[2]
PADSTR = SPECIALKEYS[3]
WARMUP_STEPS = 4000
DROPOUT_PROB = 0.1

# model configs
ENCODER_NUM = 6
DECODER_NUM = 6

DMODEL = 512
HEADNUM = 8
DFF = 2048
